{{- if .Values.stressTests.scheduler.enabled }}

apiVersion: controlplane.lab.local/v1alpha1
kind: ControlPlaneTest
metadata:
  name: scheduler-stress

spec:
  image: {{ .Values.stressTests.image }}
  replicas: {{ .Values.stressTests.replicas }}

  schedulerStress:
    enabled: true
    deploymentCount: {{ .Values.stressTests.scheduler.deploymentCount }}
    replicasPerDeployment: {{ .Values.stressTests.scheduler.replicasPerDeployment }}
    topologySpread: {{ .Values.stressTests.scheduler.topologySpread }}

{{- end }}