//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerETCDStressSpec) DeepCopyInto(out *APIServerETCDStressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerETCDStressSpec.
func (in *APIServerETCDStressSpec) DeepCopy() *APIServerETCDStressSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerETCDStressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneTest) DeepCopyInto(out *ControlPlaneTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneTest.
func (in *ControlPlaneTest) DeepCopy() *ControlPlaneTest {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneTestList) DeepCopyInto(out *ControlPlaneTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneTestList.
func (in *ControlPlaneTestList) DeepCopy() *ControlPlaneTestList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneTestSpec) DeepCopyInto(out *ControlPlaneTestSpec) {
	*out = *in
	out.ResourcesPerPod = in.ResourcesPerPod
	out.CustomLabel = in.CustomLabel
	in.SchedulerStress.DeepCopyInto(&out.SchedulerStress)
	out.APIServerETCDStress = in.APIServerETCDStress
	out.ControllerManagerStress = in.ControllerManagerStress
	out.OperatorStress = in.OperatorStress
	out.PodLifecycleStorm = in.PodLifecycleStorm
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneTestSpec.
func (in *ControlPlaneTestSpec) DeepCopy() *ControlPlaneTestSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneTestStatus) DeepCopyInto(out *ControlPlaneTestStatus) {
	*out = *in
	if in.DeploymentNames != nil {
		in, out := &in.DeploymentNames, &out.DeploymentNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMapNames != nil {
		in, out := &in.ConfigMapNames, &out.ConfigMapNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretNames != nil {
		in, out := &in.SecretNames, &out.SecretNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastStatusUpdate.DeepCopyInto(&out.LastStatusUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneTestStatus.
func (in *ControlPlaneTestStatus) DeepCopy() *ControlPlaneTestStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerManagerStressSpec) DeepCopyInto(out *ControllerManagerStressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerManagerStressSpec.
func (in *ControllerManagerStressSpec) DeepCopy() *ControllerManagerStressSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerManagerStressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLabelSpec) DeepCopyInto(out *CustomLabelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLabelSpec.
func (in *CustomLabelSpec) DeepCopy() *CustomLabelSpec {
	if in == nil {
		return nil
	}
	out := new(CustomLabelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorSpec) DeepCopyInto(out *LabelSelectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorSpec.
func (in *LabelSelectorSpec) DeepCopy() *LabelSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorInformerSpec) DeepCopyInto(out *OperatorInformerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorInformerSpec.
func (in *OperatorInformerSpec) DeepCopy() *OperatorInformerSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorInformerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorReconcileSpec) DeepCopyInto(out *OperatorReconcileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorReconcileSpec.
func (in *OperatorReconcileSpec) DeepCopy() *OperatorReconcileSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorReconcileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorStressSpec) DeepCopyInto(out *OperatorStressSpec) {
	*out = *in
	out.Reconcile = in.Reconcile
	out.Informer = in.Informer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorStressSpec.
func (in *OperatorStressSpec) DeepCopy() *OperatorStressSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorStressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLifecycleStormSpec) DeepCopyInto(out *PodLifecycleStormSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLifecycleStormSpec.
func (in *PodLifecycleStormSpec) DeepCopy() *PodLifecycleStormSpec {
	if in == nil {
		return nil
	}
	out := new(PodLifecycleStormSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerStressSpec) DeepCopyInto(out *SchedulerStressSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.AffinitySelector = in.AffinitySelector
	out.AntiAffinitySelector = in.AntiAffinitySelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerStressSpec.
func (in *SchedulerStressSpec) DeepCopy() *SchedulerStressSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulerStressSpec)
	in.DeepCopyInto(out)
	return out
}
