# Default values for controlplane-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

namespace: operator-system
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: newfile01/operator-k8s
  tag: v7
  pullPolicy: Always

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  port: 8443

serviceMonitor:
  enabled: true

grafana:
  namespace: monitoring-stack

prometheus:
  release: monitoring-stack

dashboards:
  enabled: true

stressTests:
  enabled: false
  # ==========================================================
  # WORKLOAD DEFINITION
  # ==========================================================
  image: nginx

  containerName: app

  deploymentCount: 10
  replicasPerDeployment: 20

  servicePort: 80
  targetPort: 80

  customLabel:
    key: stress
    value: standard

  resourcesPerPod:
    cpuRequest: "25m"
    cpuLimit: "50m"
    memoryRequest: "32Mi"
    memoryLimit: "64Mi"

  configMapCount: 20
  configMapSizeKB: 500

  secretCount: 20
  secretSizeKB: 500

  # ==========================================================
  # SCHEDULER STRESS
  # ==========================================================
  scheduler:

    enabled: true

    nodeSelector:
      minikube.k8s.io/primary: "false"

    topologySpread: true

    affinityMode: ""
    affinityKeyLabelSelector: ""
    affinityValueLabelSelector: ""

    antiAffinityMode: ""
    antiAffinityKeyLabelSelector: ""
    antiAffinityValueLabelSelector: ""

  # ==========================================================
  # API SERVER / ETCD STRESS
  # ==========================================================
  apiServerEtcd:

    enabled: true

    frequentStatusUpdates: false

    aggressiveReconcile: false
    reconcileRequeueDelay: 1000

    recreateResources: false

    # qps: 100
    # burst: 200

  # ==========================================================
  # CONTROLLER MANAGER STRESS
  # ==========================================================
  controllerManager:

    enabled: false

    recreateReplicaSets: false
    replicaRecreateDelay: 1000

    aggressiveGarbageCollection: false
    garbageCollectionDelay: 1000

  # ==========================================================
  # OPERATOR STRESS
  # ==========================================================
  operator:
    enabled: true
    profile: "standard"

    # maxConcurrent: 1

    # # qps: 100
    # # burst: 200

    # baseDelaySeconds: 1
    # maxDelaySeconds: 30

    # watchPods: true
    # watchDeployments: true
    # watchConfigMaps: true

  # ==========================================================
  # POD LIFECYCLE STORM
  # ==========================================================
  podLifecycleStorm:

    enabled: true

    deletePodsRandomly: true
    deletePodsDelay: 30000

    crashLoopSimulation: false # force le container à exécuter "exit 1" 